### PR TITLE
Update for React 0.14.x

### PR DESCRIPTION
**Pull request by entotsu**
Thank you for this great library.

Now that React 0.14.x is almost here, we should make sure reaxt works with it.

### CODE REVIEW

**Comment by TattdCodeMonkey** [comment]
Should `react-dom` be added to the `package.json` with the upgrade of `react` to v0.14?

**Comment by CD1212** [comment]
I am having problems getting Reaxt to work with 0.14.0. I had everything working in my Phoenix app, with ES6 and Babel but before and after applying the diffs in this merge request I still get an error along the lines of:
```
JS Exception : Error: Invariant Violation: MyComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
``` 

From the error I would think this related to using `export class MyComponent``` but since this seemed to work fine with 0.13.0 I can't work out whats wrong.

Does anyone have any ideas?

**Comment by CD1212** [comment]
I tried removing node_modules in case another version of React was lingering, which sadly had no effect.

If I override `reaxt_server_render` this solves the issue, although client rendering fails and prevents props being passed in.

```
module.exports = {
  tracker: React.createElement(Tracker),
  reaxt_server_render: function(path, render) {
    render(<Tracker />)
  }
}
```

So it definitely seems like some aspect of Reaxt is incompatible with 0.14 outside of the `react-dom` updates in this pull request.

**Comment by awetzel** [comment]
Hello CD1212, I tried some approaches, but have to found yet the source of the problem. I will update Reaxt for react 0.14 next month but currently I have too little time. 
Thank you for your PR, but currently I think a bit of work is necessary to ensure compatibility with 0.14.

**Comment by ssboisen** [comment]
Hi @awetzel, Any update on this?

**Comment by Thog** [comment]
Unneeded because of https://github.com/kbrw/reaxt/commit/24933dfad5d67b6f5415ed6047ab1c2d62eda4e7

**Pull request closed without merging**
